"""add_order_and_orderitem-table

Revision ID: a6a0d8fc768b
Revises: bbfe4fbcd6b3
Create Date: 2026-05-19 10:42:32.490115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = 'a6a0d8fc768b'
down_revision: Union[str, Sequence[str], None] = 'bbfe4fbcd6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: Creates orders and order_items tables securely."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. CREATE THE HEAD-LEVEL ORDERS LEDGER TABLE
    op.create_table(
        'orders',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        # FIXED: Replaced sqlmodel AutoString with safe sa.String()
        sa.Column('invoice_number', sa.String(), nullable=False),
        sa.Column('sub_total', sa.Float(), nullable=False),
        sa.Column('total_tax', sa.Float(), nullable=False),
        sa.Column('grand_total', sa.Float(), nullable=False),
        sa.Column('payment_method', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('cashier_id', sa.Uuid(), nullable=False),
        # Restrict system drop operations if the operator table goes missing
        sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. APPLY PERFORMANCE INDEX GUARDS ON ORDERS TABLE
    # Batch alter ensures structural SQLite alignment during index attachments
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)
        # Invoice numbers must be strictly unique to avoid cross-checkout pollution
        batch_op.create_index(batch_op.f('ix_orders_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    # 3. CREATE THE DEPENDENT TRANSACTION LINE ITEM ARCHIVE TABLE
    op.create_table(
        'order_items',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=False),
        sa.Column('cost_price', sa.Float(), nullable=False),
        sa.Column('tax_rate', sa.Float(), nullable=False),
        sa.Column('line_total', sa.Float(), nullable=False),
        sa.Column('order_id', sa.Uuid(), nullable=False),
        sa.Column('product_id', sa.Uuid(), nullable=False),
        # CASCADE: If a receipt header is hard deleted, flush its corresponding list components
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        # RESTRICT: Prevent structural deletion of a base inventory catalog entry if it's tied to an active receipt
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )

    # 4. APPLY FK INDEX GUARDS ON THE LINE ITEMS TABLE TO OPTIMIZE RELATIONSHIP JOINS
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: Destroys tables and indexes in reverse-topological dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. PURGE DEPENDENT ORDER_ITEMS INDEXES AND TABLE FIRST
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_id'))

    op.drop_table('order_items')

    # 2. PURGE ROOT ORDER TRACKING INDEXES AND TABLE LAST
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_created_at'))

    op.drop_table('orders')
    # ### end Alembic commands ###