"""add_sales_product_pricing_table

Revision ID: bbfe4fbcd6b3
Revises: 1a37f989a348
Create Date: 2026-05-18 01:17:06.123300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbfe4fbcd6b3'
down_revision: Union[str, Sequence[str], None] = '1a37f989a348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_product_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_product_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_product_product_id'), ['product_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_product_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_product_is_active'))
        batch_op.drop_index(batch_op.f('ix_sales_product_id'))

    op.drop_table('sales_product')
    # ### end Alembic commands ###
